### ISSUE TITLE
Can't attach EULA to DMG in Big Sur

### ISSUE THREAD

**Issue by Aleksid1** [create-dmg/create-dmg#109]
hditul flatten/unflatten verbs are deprecated and removed in macOS Big Sur. So it's not possible to attach EULA to a DMG in Big Sur. I saw alternative solution here:
developer.apple.com/forums/thread/668084

Please fix it.

**Comment by aonez** [comment]
@Aleksid1 you've managed to use the method in the link?

**Comment by Aleksid1** [comment]
No, I couldn't. I've understood an idea with hdiutil udifrez , but I couldn't find complete files with examples: my-eula.plist.template and my-eula.plist

**Comment by aonez** [comment]
Reading at the post, you should extract that `PLIST` using:

```sh
hdiutil udifderez -xml <YOUR_DMG_PATH>
```

Then introduce your EULA content there.

It's a little tricky because you have mixed steps in the main post and in an answer:
https://developer.apple.com/forums/thread/668084?answerId=652142022#652142022

I'm willing to bring this fix to `create-dmg`. Thanks for the tip @Aleksid1.

**Comment by Aleksid1** [comment]
Thanks for your advice! Regrettably I still can't perform these steps correctly.
I would grateful for your help with modifiying the script. I can check it and inform you about a result. I have 2 Macs with Big Sur - Intel and M1.

**Comment by aonez** [comment]
You can already test it: https://github.com/create-dmg/create-dmg/commit/f75cc032d77672adab60cebd49db000a8ff7446a

Just clone the repository and check it out.

**Comment by Aleksid1** [comment]
Thank you very much! License was attached to a DMG correctly. 
I tested on Macbook Air M1 / macOS 11.1 Big Sur
