### ISSUE TITLE
ERROR: unable to proceed with final disk image creation because the interstitial disk image was not found

### ISSUE THREAD

**Issue by sptrakesh** [create-dmg/create-dmg#164]
Hello,

Getting the above error consistently when attempting to create a DMG using the following invocation (Sonoma 14.2.1, create-dmg installed via brew):
```
create-dmg \
    --icon background.jpg 144 144 \
    --volname "MoviePlayer Installer" \
    --volicon Icon.icns \
    --filesystem APFS \
    --app-drop-link 416 144 \
    --hdiutil-quiet \
    MoviePlayer.dmg /tmp/make_dmg
```

The log is as follows:
```
Creating disk image...
Mounting disk image...
Device name:     /dev/disk4
Searching for mounted interstitial disk image using /dev/disk4s... 
ERROR: unable to proceed with final disk image creation because the interstitial disk image was not found.
The interstitial disk image will likely be mounted and will need to be cleaned up manually.
```

**Comment by emjoseph** [comment]
Seeing a similar error as well on Sonoma 14.2.1.
Code:
```
create-dmg \
--volname "App Installer" \
--window-pos 200 120 \
--window-size 760 552 \
--icon-size 130 \
--text-size 13 \
--filesystem "APFS" \
--background "background.png" \
--icon "MyApp.app" 130 303 \
--hide-extension "MyApp.app" \
--app-drop-link 630 303 \
--codesign {My Code Sign Info} \
"MyAppInstaller.dmg" \
"./source/"
```

```
Creating disk image...
....................................................................................................................................................
created: /Users/emjoseph/MyApp/MacDistribution/rw.14059.MyAppInstaller.dmg
Mounting disk image...
Device name:     /dev/disk4
Searching for mounted interstitial disk image using /dev/disk4s...
ERROR: unable to proceed with final disk image creation because the interstitial disk image was not found.
The interstitial disk image will likely be mounted and will need to be cleaned up manually.
```

If I switch to HFS+ I see this:
```
created: /Users/emjoseph/MyApp/MacDistribution/rw.13484.MyAppInstaller.dmg
Mounting disk image...
Device name:     /dev/disk4
Searching for mounted interstitial disk image using /dev/disk4s...
Mount dir:
/Volumes/dmg.agS6je
Copying background file 'background.png'...
mkdir:
/Volumes/dmg.agS6je: No such file or directory
```

**Comment by fsantini** [comment]
I just had the same problem. For some reason, the system started returning a newline before /Volumes/dmg.XXXX. I patched it by changing line 149 of the script (inside `find_mount_dir()`) to:
`echo "${found_dir:1}"`
This should probably be written in a portable way (remove characters before the first / in the string?) but it's an easy workaround for the moment.

**Comment by gnattu** [comment]
After looking at it I had some observations but unfortunately no easy fix.

The current hardcoded values for setting `DEV_NAME` is wrong for APFS disk images. The disk images for APFS does not only have only one, but multiple disks (as APFS Volumes) in it. 

More specifically this line:

https://github.com/create-dmg/create-dmg/blob/b62ae1dd11ac0a3e17ea944384104450d800f04c/create-dmg#L420-L420

I assumes the first line will return the disk to be mounted, but it is wrong. 

This is probably what you will get for an APFS image:

```
/dev/disk4	GUID_partition_scheme	
/dev/disk4s1	7C3457EF-0000-11AA-AA11-00306543ECAC	
/dev/disk5	EF57347C-0000-11AA-AA11-00306543ECAC	
/dev/disk5s1	41504653-0000-11AA-AA11-00306543ECAC	/Volumes/dmg.qUZVr1
```

As you see, from the output above, actually the one that comes from the **last line** is the one we want to search for.

This also explains what @fsantini found, that in some cases, there is a newline before the actual mount point: because the disk name matching may match a disk without mount point at first, then in the second line, with a disk that have the mount point, hence the newline.

My suggestion would be change the `sed 1q` to `tail -n 1`, but I'm not very sure if it will work for everyone. It works for me to generate an APFS image.

**Comment by mjmeijer** [comment]
Changing from APFS to HFS+ proceeds further, but I get stuck in unmounting the disk:

```
Done running the AppleScript...
Fixing permissions...
Done fixing permissions
Skipping blessing on sandbox
Deleting .fseventsd
Unmounting disk image...
hdiutil: couldn't unmount "disk10" - Resource busy
Wait a moment...
Unmounting disk image...
hdiutil: couldn't unmount "disk10" - Resource busy
Wait a moment...
Unmounting disk image...
hdiutil: couldn't unmount "disk10" - Resource busy
%
```

**Comment by PrimozGodec** [comment]
I have the same issue on HFS+ (newline before /Volumes/dmg.XXXX). What would be a generic solution for that? @gnattu, if I understand correctly, your solution is for APFS? Would it be enough to remove any character before the first `/` (or can this solution have some issue in certain cases)?

**Comment by aonez** [comment]
Please check the new release: https://github.com/create-dmg/create-dmg/releases/tag/v1.2.2
